config/routes.rb
OrderEdi::Application.routes.draw do
  
  devise_for :users
  resources :orders
  resources :audits

  root :to => "static_pages#home"

end

app/models/order.rb
class Order < ActiveRecord::Base
  audited
  attr_accessible :billing_address, :customer_name, :description, :item_name, :price, :user_id
  belongs_to :user
  validates :billing_address, :customer_name, :description, :item_name, :price, presence: true
  
  STATUS = {pending: 'pending', completed: 'completed'}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  audited
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController
  # GET /audits
  # GET /audits.json
  def index
    @audits = Audited::Adapters::ActiveRecord::Audit.where(user_id: current_user.id)
    
    if request.xhr?
      return render partial: 'audits'
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @audits }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :find_resource, except: [:index, :new, :create]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders

    if request.xhr?
      return render partial: 'orders'
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        Order::Schedular.process(@order)
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private

  def find_resource
    @order = current_user.orders.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :authenticate_user!
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/audits/_audits.html.erb
<% @audits.each do |audit| %>
  <tr>
    <td><%= audit.auditable_type %></td>
    <td><%= audit.action %></td>
    <td><%= audit.audited_changes %></td>
  </tr>
<% end %>

app/views/audits/index.html.erb
<h1>Listing audits</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Type</th>
      <th>Action</th>
      <th>Changes</th>
    </tr>
  </thead>
  <tbody id="refreshable">
    <%= render :partial => "audits" %>
  </tbody>
</table>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-narrow">
      <div class="masthead">
        <%= render 'layouts/user_header' %>
        <h3 class="muted"><%= link_to "Order Management System", root_path %></h3>
        <% if user_signed_in? %>
        <div class="navbar">
          <div class="navbar-inner">
            <ul class="nav">
              <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
              <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to "Orders", orders_path %></li>
              <li class="<%= 'active' if current_page?(audits_path) %>"><%= link_to "User Audits", audits_path %></li>
            </ul>
          </div>
        </div>
        <%end%>
      </div>
      <hr />
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="border-form-div">
  <%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
        <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.text_field :customer_name, :autofocus => true, :placeholder => 'Customer Name' %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.text_field :item_name, :autofocus => true, :placeholder => 'Item Name' %>
    <%= f.text_field :price, :autofocus => true, :placeholder => 'Item Price' %>
    <%= f.text_field :description, :autofocus => true, :placeholder => 'Item Description' %>
    <%= f.text_field :billing_address, :autofocus => true, :placeholder => 'Billing Address' %>
     <br/>
    <%= f.submit "Submit", :class=>'btn btn-primary' %>
<% end %>
</div

app/views/orders/_orders.html.erb
<% @orders.each do |order| %>
  <tr>
    <td><%= link_to order.id, order_path(order) %></td>
    <td><%= order.status %></td>
    <td><%= order.customer_name %></td>
    <td><%= order.item_name %></td>
    <td><%= order.price %></td>
    <td><%= order.billing_address %></td>
    <td><%=l order.created_at %></td>
    <td>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_order_path(order), :class => 'btn btn-mini' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  order_path(order),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_order_path,
            :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:customer_name) %></th>
      <th><%= model_class.human_attribute_name(:item) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:billing_address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id="refreshable">
    <%= render :partial => "orders" %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => 'Order info' %></h1>
</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Customer name:</b>
  <%= @order.customer_name %>
</p>

<p>
  <b>Status:</b>
  <%= @order.status %>
</p>

<p>
  <b>User:</b>
  <%= @order.user_id %>
</p>

<p>
  <b>Item name:</b>
  <%= @order.item_name %>
</p>

<p>
  <b>Price:</b>
  <%= @order.price %>
</p>

<p>
  <b>Description:</b>
  <%= @order.description %>
</p>

<p>
  <b>Billing Address:</b>
  <%= @order.billing_address %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1>Welcome to home page, trusted user!</h1>
    <p class="lead">
      You can place new order from here.
    </p>
    <%= link_to "New Order", new_order_path, :class => 'btn btn-primary' %>
  <% else %>
    <h1>Welcome, new user!</h1>
    <p class="lead">
      You must sign in or sign up before you can access the app features.
    </p>
    <div class="row-fluid">
      <div class="span6">
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
      </div>
      <div class="span6">
        <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>